apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: quarkus-trusted-app 
  janus-idp.io/tekton: quarkus-trusted-app
  backstage.io/kubernetes-id: quarkus-trusted-app
  backstage.io/kubernetes-namespace: rodan-demo 
  app.kubernetes.io/part-of: quarkus-trusted-app
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml