apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-trusted-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-trusted-app 
  name: quarkus-trusted-app
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: quarkus-trusted-app 
